[package]

name = "just_run"
version = "0.0.1"
authors = [ "Nolan Price <nolan@nolanprice.com>" ]

[dependencies]
rand = "*"
time = "*"

[dependencies.sdl2]
version = "0.35.0"
features = ["mixer", "ttf", "unsafe_textures"]
